name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CC: gcc-9
      CXX: g++-9

    steps:
    - uses: actions/checkout@v3
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: setup
      run: sudo apt-get install ninja-build

    - name: apt install dependency
      run: |
        sudo apt-get -y install valgrind
        sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev

    - name: build
      run: |
        echo "Building project..."
        mkdir build && cd build
        cmake .. -GNinja
    - name: graph_gtests
      run: |
        cd build
        ninja tests

    - name: valgrind
      run: |
        cd build
        valgrind tests/analysis_tests -s
        valgrind tests/graph_tests -s

