name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: setup
      run: sudo apt-get install ninja-build
    - name: build
      run: |
        echo "Building project..."
        mkdir build && cd build
        cmake .. -GNinja
    - name: graph_gtests
      run: |
        cd build
        ninja tests

